# File required to load packs as Forge mods.
# Find more information on toml format v0.5.0 here:  https://github.com/toml-lang/toml

# Forge settings, don't touch!
modLoader="javafml"
loaderVersion="[36,)"

# The license for your pack. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]] 
# The ID of your pack.
modId="acmearmory"
# Version number.  Can be whatever format you'd like.
version="VV2.0Beta"
 # Display name for the pack in the in-game mods list.
displayName="ACME Heavy Industries Pack for Immersive Vehicles"
# A URL for the "homepage" for this pack, displayed in the mod UI.
displayURL="https://www.curseforge.com/minecraft/mc-mods/acme-heavy-industries-pack"
# Pack logo.
logoFile="vingette.png"
# The description text for the pack (multi line!)
description='''
A companion to the official pack; this centers mainly around military aviation from all eras however is not limited solely to it.
'''

[[mods]]
# The ID of your pack.
modId="acmebase"
# Version number.  Can be whatever format you'd like.
version="VV2.0Beta"
 # Display name for the pack in the in-game mods list.
displayName="ACME Heavy Industries"
# A URL for the "homepage" for this pack, displayed in the mod UI.
displayURL="https://www.curseforge.com/minecraft/mc-mods/acme-heavy-industries-pack"
# Pack logo.
logoFile="vingette.png"
# The description text for the pack (multi line!)
description='''
A companion pack to the official pack for Immersive Vehicles.
'''

[[mods]]
# The ID of your pack.
modId="acmecivil"
# Version number.  Can be whatever format you'd like.
version="VV2.0Beta"
 # Display name for the pack in the in-game mods list.
displayName="ACME H.I. Civilian Sector"
# A URL for the "homepage" for this pack, displayed in the mod UI.
displayURL="https://www.curseforge.com/minecraft/mc-mods/acme-heavy-industries-pack"
# Pack logo.
logoFile="vingette.png"
# The description text for the pack (multi line!)
description='''
Civilian Sector of ACME Heavy Industries.
'''

[[mods]]
# The ID of your pack.
modId="acmetesting"
# Version number.  Can be whatever format you'd like.
version="V2.0Beta"
 # Display name for the pack in the in-game mods list.
displayName="ACME H.I. Experimental Division"
# A URL for the "homepage" for this pack, displayed in the mod UI.
displayURL="https://www.curseforge.com/minecraft/mc-mods/acme-heavy-industries-pack"
# Pack logo.
logoFile="vingette.png"
# The description text for the pack (multi line!)
description='''
Unfinished, or experimental features. Liable to change.
Also used as an update buffer for major changes to existing vehicles.
'''

[[dependencies.acmebase]]
    modId="mts"
    mandatory=true
    versionRange="[22.12.0,)"
    ordering="NONE"
    side="BOTH"

